"""Ablation study runner for EIT touch classification.

Systematically trains and evaluates models with different noise component
combinations to identify which noise sources most impact robustness.

Supported experiments:
1. **Noise ablation** – train/test with each noise component toggled on/off.
   Requires per-configuration datasets generated by the MATLAB pipeline.
2. **Train/test noise mismatch** – train on clean, evaluate on noisy and
   vice-versa using a single dataset containing both clean and noisy vectors.
3. **CNN ablation** – repeat any of the above with the 1D-CNN model.
"""

import itertools
import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from configs.loader import load_config
from data.load_dataset import load_mat_dataset, prepare_splits
from models.baselines import get_baseline, train_baseline
from models.cnn1d import EITConv1D
from sklearn.metrics import accuracy_score, f1_score
from train import train_cnn

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# Noise component names matching MATLAB config
NOISE_COMPONENTS = [
    "gaussian",
    "contact_impedance",
    "electrode_bias",
    "quantisation",
]


@dataclass
class AblationResult:
    """Result from a single ablation experiment."""

    noise_config: dict[str, bool]
    model_name: str
    train_accuracy: float
    val_accuracy: float
    test_accuracy: float
    test_f1_macro: float
    description: str = ""


@dataclass
class AblationStudy:
    """Container for full ablation study results."""

    results: list[AblationResult] = field(default_factory=list)

    def to_dataframe(self) -> pd.DataFrame:
        """Convert results to a pandas DataFrame for analysis."""
        rows = []
        for r in self.results:
            row = {
                "model": r.model_name,
                "description": r.description,
                "train_acc": r.train_accuracy,
                "val_acc": r.val_accuracy,
                "test_acc": r.test_accuracy,
                "test_f1": r.test_f1_macro,
            }
            for comp in NOISE_COMPONENTS:
                row[f"noise_{comp}"] = r.noise_config.get(comp, False)
            rows.append(row)
        return pd.DataFrame(rows)

    def save(self, output_path: Path) -> None:
        """Save ablation results to CSV."""
        df = self.to_dataframe()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(output_path, index=False)
        logger.info(f"Ablation results saved to {output_path}")


def generate_ablation_configs() -> list[tuple[str, dict[str, bool]]]:
    """Generate all noise component combinations for ablation.

    Returns:
        List of (description, config) tuples.  Includes:
        - All off (clean baseline)
        - Each component individually (single-component)
        - Leave-one-out (all except one)
        - All on (full noise)
    """
    configs: list[tuple[str, dict[str, bool]]] = []

    # Clean baseline (no noise)
    configs.append(("clean", {c: False for c in NOISE_COMPONENTS}))

    # Individual components (single-component training)
    for comp in NOISE_COMPONENTS:
        config = {c: False for c in NOISE_COMPONENTS}
        config[comp] = True
        configs.append((f"only_{comp}", config))

    # Leave-one-out (all except one component)
    for comp in NOISE_COMPONENTS:
        config = {c: True for c in NOISE_COMPONENTS}
        config[comp] = False
        configs.append((f"without_{comp}", config))

    # All on (full noise model)
    configs.append(("all_noise", {c: True for c in NOISE_COMPONENTS}))

    return configs


def _evaluate_sklearn(
    model: object,
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
) -> tuple[float, float, float, float]:
    """Return (train_acc, val_acc, test_acc, test_f1) for an sklearn model."""
    train_acc = accuracy_score(y_train, model.predict(X_train))
    val_acc = accuracy_score(y_val, model.predict(X_val))
    y_pred_test = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred_test)
    test_f1 = f1_score(y_test, y_pred_test, average="macro")
    return train_acc, val_acc, test_acc, test_f1


def _evaluate_cnn(
    model: EITConv1D,
    X: np.ndarray,
    y: np.ndarray,
    device: str = "cpu",
) -> tuple[float, float]:
    """Return (accuracy, f1_macro) for a CNN model on a given split."""
    model.eval()
    X_t = torch.from_numpy(X).float().to(device)
    with torch.no_grad():
        preds = model(X_t).argmax(dim=1).cpu().numpy()
    return float(accuracy_score(y, preds)), float(f1_score(y, preds, average="macro"))


def run_ablation(
    data_path: Path,
    model_name: str = "random_forest",
    seed: int = 42,
    run_all_configs: bool = False,
) -> AblationStudy:
    """Run the ablation study.

    When ``run_all_configs`` is *True*, the function iterates over every
    noise configuration returned by :func:`generate_ablation_configs`.  This
    requires per-config datasets named ``eit_dataset_<config>.mat`` in the
    same directory as ``data_path``.

    When *False* (default), it performs the four mismatch experiments using
    only the clean and full-noisy data, which is available from a single
    dataset file.

    Args:
        data_path: Path to the dataset .mat file (must contain both
                   clean and noisy vectors).
        model_name: Model to train (any value accepted by
                    :func:`models.baselines.get_baseline` **or** ``'cnn1d'``).
        seed: Random seed.
        run_all_configs: If *True*, run every noise configuration.

    Returns:
        Completed :class:`AblationStudy`.
    """
    cfg = load_config()
    logger.info(f"Starting ablation study with model: {model_name}")

    np.random.seed(seed)
    torch.manual_seed(seed)

    # Load full dataset (both clean and noisy available)
    X_noisy, y = load_mat_dataset(data_path, use_noisy=True)
    X_clean, _ = load_mat_dataset(data_path, use_noisy=False)

    dataset_noisy = prepare_splits(X_noisy, y, random_state=seed)
    dataset_clean = prepare_splits(X_clean, y, random_state=seed)

    study = AblationStudy()

    # Helper to train and wrap results
    def _run_experiment(
        X_train: np.ndarray,
        y_train: np.ndarray,
        X_val: np.ndarray,
        y_val: np.ndarray,
        X_test: np.ndarray,
        y_test: np.ndarray,
        noise_cfg: dict[str, bool],
        description: str,
    ) -> None:
        if model_name == "cnn1d":
            model, _ = train_cnn(
                X_train,
                y_train,
                X_val,
                y_val,
                epochs=cfg["training"]["epochs"],
                batch_size=cfg["training"]["batch_size"],
                lr=cfg["training"]["learning_rate"],
                weight_decay=cfg["training"]["weight_decay"],
                scheduler_patience=cfg["training"]["scheduler_patience"],
                scheduler_factor=cfg["training"]["scheduler_factor"],
                early_stopping_patience=cfg["training"]["early_stopping_patience"],
            )
            train_acc, _ = _evaluate_cnn(model, X_train, y_train)
            val_acc, _ = _evaluate_cnn(model, X_val, y_val)
            test_acc, test_f1 = _evaluate_cnn(model, X_test, y_test)
        else:
            model = get_baseline(model_name, random_state=seed)
            model = train_baseline(model, X_train, y_train)
            train_acc, val_acc, test_acc, test_f1 = _evaluate_sklearn(
                model, X_train, y_train, X_val, y_val, X_test, y_test
            )

        study.results.append(
            AblationResult(
                noise_config=noise_cfg,
                model_name=model_name,
                train_accuracy=train_acc,
                val_accuracy=val_acc,
                test_accuracy=test_acc,
                test_f1_macro=test_f1,
                description=description,
            )
        )
        logger.info(
            f"  {description}: acc={test_acc:.4f}, f1={test_f1:.4f}"
        )

    # ── Core mismatch experiments ──────────────────────────────────────
    all_off = {c: False for c in NOISE_COMPONENTS}
    all_on = {c: True for c in NOISE_COMPONENTS}

    logger.info("Exp 1/4: train_clean → eval_clean")
    _run_experiment(
        dataset_clean.X_train, dataset_clean.y_train,
        dataset_clean.X_val, dataset_clean.y_val,
        dataset_clean.X_test, dataset_clean.y_test,
        all_off, "train_clean_eval_clean",
    )

    logger.info("Exp 2/4: train_clean → eval_noisy")
    _run_experiment(
        dataset_clean.X_train, dataset_clean.y_train,
        dataset_clean.X_val, dataset_clean.y_val,
        dataset_noisy.X_test, dataset_noisy.y_test,
        all_off, "train_clean_eval_noisy",
    )

    logger.info("Exp 3/4: train_noisy → eval_noisy")
    _run_experiment(
        dataset_noisy.X_train, dataset_noisy.y_train,
        dataset_noisy.X_val, dataset_noisy.y_val,
        dataset_noisy.X_test, dataset_noisy.y_test,
        all_on, "train_noisy_eval_noisy",
    )

    logger.info("Exp 4/4: train_noisy → eval_clean")
    _run_experiment(
        dataset_noisy.X_train, dataset_noisy.y_train,
        dataset_noisy.X_val, dataset_noisy.y_val,
        dataset_clean.X_test, dataset_clean.y_test,
        all_on, "train_noisy_eval_clean",
    )

    # ── Per-component ablation (optional) ──────────────────────────────
    if run_all_configs:
        for desc, noise_cfg in generate_ablation_configs():
            mat_stem = f"eit_dataset_{desc}"
            mat_file = data_path.parent / f"{mat_stem}.mat"
            if not mat_file.exists():
                logger.warning(f"Skipping {desc}: {mat_file} not found")
                continue

            logger.info(f"Ablation config: {desc}")
            X_cfg, y_cfg = load_mat_dataset(mat_file, use_noisy=True)
            ds = prepare_splits(X_cfg, y_cfg, random_state=seed)
            _run_experiment(
                ds.X_train, ds.y_train,
                ds.X_val, ds.y_val,
                ds.X_test, ds.y_test,
                noise_cfg, desc,
            )

    logger.info("Ablation study complete.")
    return study


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Run ablation study.")
    parser.add_argument(
        "--data-path",
        type=Path,
        default=None,
        help="Path to dataset .mat file (default: from config.yaml).",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="random_forest",
        choices=["svm", "random_forest", "mlp", "cnn1d"],
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/tables/ablation_results.csv"),
    )
    parser.add_argument(
        "--all-configs",
        action="store_true",
        help="Run every noise combination (requires per-config datasets).",
    )
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    cfg = load_config()
    data_path = args.data_path or Path(cfg["data"]["path"])

    study = run_ablation(
        data_path,
        model_name=args.model,
        seed=args.seed,
        run_all_configs=args.all_configs,
    )
    study.save(args.output)

    # Print summary
    df = study.to_dataframe()
    print("\n=== Ablation Study Summary ===")
    print(df[["description", "test_acc", "test_f1"]].to_string(index=False))
