"""Ablation study runner for EIT touch classification.

Systematically trains and evaluates models with different noise component
combinations to identify which noise sources most impact robustness.

Supported experiments:
1. **Python-side noise ablation** – applies noise on-the-fly during training
   with per-component toggling. No separate MATLAB datasets required.
2. **Train/test noise mismatch** – train on clean, evaluate on noisy and
   vice-versa using a single dataset containing both clean and noisy vectors.
3. **CNN ablation** – repeat any of the above with the 1D-CNN model.
4. **MATLAB dataset ablation** (legacy) – uses per-configuration .mat files
   generated by the MATLAB pipeline when available.
"""

from __future__ import annotations

import itertools
import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from configs.loader import load_config
from models.baselines import get_baseline, train_baseline
from models.cnn1d import EITConv1D
from sklearn.metrics import accuracy_score, f1_score
from train import train_cnn

from data.load_dataset import load_mat_dataset, prepare_splits
from data.noise import NoiseConfig, apply_noise_batch_vectorised

logger = logging.getLogger(__name__)

# Noise component names matching MATLAB config
NOISE_COMPONENTS = [
    "gaussian",
    "contact_impedance",
    "electrode_bias",
    "quantisation",
]


@dataclass
class AblationResult:
    """Result from a single ablation experiment."""

    noise_config: dict[str, bool]
    model_name: str
    train_accuracy: float
    val_accuracy: float
    test_accuracy: float
    test_f1_macro: float
    description: str = ""
    component_order: tuple[str, ...] | None = None


@dataclass
class AblationStudy:
    """Container for full ablation study results."""

    results: list[AblationResult] = field(default_factory=list)

    def to_dataframe(self) -> pd.DataFrame:
        """Convert results to a pandas DataFrame for analysis."""
        rows = []
        for r in self.results:
            row = {
                "model": r.model_name,
                "description": r.description,
                "train_acc": r.train_accuracy,
                "val_acc": r.val_accuracy,
                "test_acc": r.test_accuracy,
                "test_f1": r.test_f1_macro,
                "noise_order": " > ".join(r.component_order or ()),
                "noise_n_components": sum(r.noise_config.values()),
            }
            for comp in NOISE_COMPONENTS:
                row[f"noise_{comp}"] = r.noise_config.get(comp, False)
            rows.append(row)
        return pd.DataFrame(rows)

    def save(self, output_path: Path) -> None:
        """Save ablation results to CSV."""
        df = self.to_dataframe()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(output_path, index=False)
        logger.info(f"Ablation results saved to {output_path}")


def generate_ablation_configs() -> list[tuple[str, NoiseConfig]]:
    """Generate all physically-meaningful noise configs for ablation.

    Returns:
        List of (description, NoiseConfig) tuples. Includes every non-empty
        component subset (1/2/3/4 components) and all physically admissible
        orderings under these rules:
        - Quantisation is always last when enabled.
        - Contact impedance is applied before electrode bias when both enabled.
    """
    configs: list[tuple[str, NoiseConfig]] = []

    for n_components in range(1, len(NOISE_COMPONENTS) + 1):
        for subset in itertools.combinations(NOISE_COMPONENTS, n_components):
            for order in _physically_valid_orders(subset):
                cfg = NoiseConfig(
                    enabled=True,
                    gaussian_enabled="gaussian" in subset,
                    contact_impedance_enabled="contact_impedance" in subset,
                    electrode_bias_enabled="electrode_bias" in subset,
                    quantisation_enabled="quantisation" in subset,
                    component_order=order,
                )
                subset_str = "+".join(subset)
                order_str = "->".join(order)
                configs.append((f"subset_{subset_str}__order_{order_str}", cfg))

    return configs


def _physically_valid_orders(components: tuple[str, ...]) -> list[tuple[str, ...]]:
    """Return physically constrained component orderings for a subset.

    Rules:
        1) quantisation is fixed as the last stage when present.
        2) contact impedance precedes electrode bias when both are present.
    """
    active = list(components)
    includes_quant = "quantisation" in active

    non_quant = [c for c in active if c != "quantisation"]
    candidate_orders = list(itertools.permutations(non_quant))
    valid_non_quant: list[tuple[str, ...]] = []

    for order in candidate_orders:
        if (
            "contact_impedance" in order
            and "electrode_bias" in order
            and order.index("contact_impedance") > order.index("electrode_bias")
        ):
            continue
        valid_non_quant.append(order)

    if includes_quant:
        return [order + ("quantisation",) for order in valid_non_quant]
    return valid_non_quant


def _evaluate_sklearn(
    model: object,
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
) -> tuple[float, float, float, float]:
    """Return (train_acc, val_acc, test_acc, test_f1) for an sklearn model."""
    train_acc = accuracy_score(y_train, model.predict(X_train))
    val_acc = accuracy_score(y_val, model.predict(X_val))
    y_pred_test = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred_test)
    test_f1 = f1_score(y_test, y_pred_test, average="macro")
    return train_acc, val_acc, test_acc, test_f1


def _evaluate_cnn(
    model: EITConv1D,
    X: np.ndarray,
    y: np.ndarray,
    device: str = "cpu",
    batch_size: int = 512,
) -> tuple[float, float]:
    """Return (accuracy, f1_macro) for a CNN model on a given split."""
    model.eval()
    all_preds = []
    n = len(X)
    with torch.no_grad():
        for start in range(0, n, batch_size):
            X_batch = torch.from_numpy(X[start : start + batch_size]).float().to(device)
            preds = model(X_batch).argmax(dim=1).cpu().numpy()
            all_preds.append(preds)
    all_preds = np.concatenate(all_preds)
    return float(accuracy_score(y, all_preds)), float(
        f1_score(y, all_preds, average="macro")
    )


def run_ablation(
    data_path: Path,
    model_name: str = "random_forest",
    seed: int = 42,
    run_all_configs: bool = False,
) -> AblationStudy:
    """Run the ablation study using Python-side noise injection.

    The study uses CLEAN data as input and applies noise on-the-fly via
    the Python noise model. This eliminates the need for separate MATLAB
    datasets for each noise configuration.

        Experiments:
                - Core mismatch (4 experiments): clean→clean, clean→noisy,
                    noisy→noisy, noisy→clean.
                - Exhaustive component/order ablation (when run_all_configs=True):
                    all non-empty component subsets (1/2/3/4 components) with all
                    physically constrained orderings.

    For CNN models, noise is applied on-the-fly during training (different
    noise realisation each epoch). For sklearn models, noise is applied once
    to the training data before fitting.

    Args:
        data_path: Path to the dataset .mat file (must contain clean vectors).
        model_name: Model to train ('cnn1d', 'svm', 'random_forest', 'mlp').
        seed: Random seed.
        run_all_configs: If True, run all subset/order ablation experiments
            using Python-side noise injection.

    Returns:
        Completed AblationStudy.
    """
    cfg = load_config()
    logger.info(f"Starting ablation study with model: {model_name}")

    # Device selection for CNN
    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info(f"Using device: {device}")

    np.random.seed(seed)
    torch.manual_seed(seed)
    if device == "cuda":
        torch.cuda.manual_seed(seed)

    # Load CLEAN data as the base (noise is applied in Python)
    X_clean, y = load_mat_dataset(data_path, use_noisy=False)

    # Also load the MATLAB-generated noisy data for the mismatch baseline
    X_noisy_matlab, _ = load_mat_dataset(data_path, use_noisy=True)

    # Use identical splits for all experiments
    dataset_clean = prepare_splits(X_clean, y, random_state=seed)
    dataset_noisy = prepare_splits(X_noisy_matlab, y, random_state=seed)

    # Full noise config (all 4 components at default severity)
    full_noise = NoiseConfig()

    study = AblationStudy()

    def _run_experiment(
        train_data: str,
        eval_data: str,
        noise_cfg: NoiseConfig | None,
        description: str,
    ) -> None:
        """Train and evaluate a single ablation experiment.

        Args:
            train_data: 'clean' uses clean splits; 'noisy_matlab' uses
                pre-generated MATLAB noisy; 'noisy_python' applies noise_cfg
                on-the-fly (CNN) or pre-applies to training data (sklearn).
            eval_data: 'clean' or 'noisy' (always uses full 4-component
                Python noise for noisy evaluation).
            noise_cfg: Noise configuration for Python-side injection.
            description: Experiment label.
        """
        # Select training data
        if train_data == "clean":
            X_tr = dataset_clean.X_train
            y_tr = dataset_clean.y_train
            X_v = dataset_clean.X_val
            y_v = dataset_clean.y_val
            train_noise_cfg = None  # No augmentation
        elif train_data == "noisy_matlab":
            X_tr = dataset_noisy.X_train
            y_tr = dataset_noisy.y_train
            X_v = dataset_noisy.X_val
            y_v = dataset_noisy.y_val
            train_noise_cfg = None  # Data is already noisy
        elif train_data == "noisy_python":
            # Use clean data; noise applied during training
            X_tr = dataset_clean.X_train
            y_tr = dataset_clean.y_train
            X_v = dataset_clean.X_val
            y_v = dataset_clean.y_val
            train_noise_cfg = noise_cfg
        else:
            raise ValueError(f"Unknown train_data: {train_data}")

        # Select evaluation data
        if eval_data == "clean":
            X_te = dataset_clean.X_test
            y_te = dataset_clean.y_test
        elif eval_data == "noisy":
            # Apply full Python noise to clean test data for consistent evaluation
            eval_rng = np.random.default_rng(seed + 999)
            X_te = apply_noise_batch_vectorised(
                dataset_clean.X_test, full_noise, rng=eval_rng
            )
            y_te = dataset_clean.y_test
        else:
            raise ValueError(f"Unknown eval_data: {eval_data}")

        # Train and evaluate
        if model_name == "cnn1d":
            model, _ = train_cnn(
                X_tr,
                y_tr,
                X_v,
                y_v,
                epochs=cfg["training"]["epochs"],
                batch_size=cfg["training"]["batch_size"],
                lr=cfg["training"]["learning_rate"],
                weight_decay=cfg["training"]["weight_decay"],
                scheduler_patience=cfg["training"]["scheduler_patience"],
                scheduler_factor=cfg["training"]["scheduler_factor"],
                early_stopping_patience=cfg["training"]["early_stopping_patience"],
                device=device,
                noise_config=train_noise_cfg,
            )
            train_acc, _ = _evaluate_cnn(model, X_tr, y_tr, device=device)
            val_acc, _ = _evaluate_cnn(model, X_v, y_v, device=device)
            test_acc, test_f1 = _evaluate_cnn(model, X_te, y_te, device=device)
        else:
            # For sklearn models, pre-apply noise to training data
            if train_noise_cfg is not None and train_noise_cfg.enabled:
                aug_rng = np.random.default_rng(seed)
                X_tr = apply_noise_batch_vectorised(X_tr, train_noise_cfg, rng=aug_rng)

            model = get_baseline(model_name, random_state=seed)
            model = train_baseline(model, X_tr, y_tr)
            train_acc, val_acc, test_acc, test_f1 = _evaluate_sklearn(
                model, X_tr, y_tr, X_v, y_v, X_te, y_te
            )

        noise_flags = (
            noise_cfg.component_flags()
            if noise_cfg
            else {c: False for c in NOISE_COMPONENTS}
        )
        study.results.append(
            AblationResult(
                noise_config=noise_flags,
                model_name=model_name,
                train_accuracy=train_acc,
                val_accuracy=val_acc,
                test_accuracy=test_acc,
                test_f1_macro=test_f1,
                description=description,
                component_order=(
                    noise_cfg.resolved_component_order() if noise_cfg else ()
                ),
            )
        )
        logger.info(f"  {description}: acc={test_acc:.4f}, f1={test_f1:.4f}")

    # ── Core mismatch experiments ──────────────────────────────────────
    logger.info("Exp 1/4: train_clean → eval_clean")
    _run_experiment("clean", "clean", None, "train_clean_eval_clean")

    logger.info("Exp 2/4: train_clean → eval_noisy")
    _run_experiment("clean", "noisy", None, "train_clean_eval_noisy")

    logger.info("Exp 3/4: train_noisy → eval_noisy (full noise, on-the-fly)")
    _run_experiment("noisy_python", "noisy", full_noise, "train_noisy_eval_noisy")

    logger.info("Exp 4/4: train_noisy → eval_clean")
    _run_experiment("noisy_python", "clean", full_noise, "train_noisy_eval_clean")

    # ── Exhaustive component/order ablation (Python-side injection) ─────
    if run_all_configs:
        configs = generate_ablation_configs()
        logger.info(
            "\n── Exhaustive component/order ablation (%d experiments) ──",
            len(configs),
        )
        for idx, (description, cfg_variant) in enumerate(configs, start=1):
            logger.info("  [%d/%d] %s", idx, len(configs), description)
            _run_experiment("noisy_python", "noisy", cfg_variant, description)

    logger.info("Ablation study complete.")
    return study


if __name__ == "__main__":
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    parser = argparse.ArgumentParser(description="Run ablation study.")
    parser.add_argument(
        "--data-path",
        type=Path,
        default=None,
        help="Path to dataset .mat file (default: from config.yaml).",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="random_forest",
        choices=["svm", "random_forest", "mlp", "cnn1d"],
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/tables/ablation_results.csv"),
    )
    parser.add_argument(
        "--all-configs",
        action="store_true",
        help=(
            "Run exhaustive ablation over all 1/2/3/4-component subsets and "
            "physically constrained component orders."
        ),
    )
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    cfg = load_config()
    data_path = args.data_path or Path(cfg["data"]["path"])

    study = run_ablation(
        data_path,
        model_name=args.model,
        seed=args.seed,
        run_all_configs=args.all_configs,
    )
    study.save(args.output)

    # Print summary
    df = study.to_dataframe()
    print("\n=== Ablation Study Summary ===")
    print(df[["description", "test_acc", "test_f1"]].to_string(index=False))
